# Generated by Django 4.2.4 on 2023-08-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='username',
            new_name='first_name',
        ),
    ]
