# Generated by Django 4.2.4 on 2023-09-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_second_name_user_surname_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='mylesmark753@gmail.com', max_length=150),
            preserve_default=False,
        ),
    ]
